[package]
name = "Milk-Backend"
version = "0.1.0"
edition = "2025"

[dependencies]
actix-web = "4.9.0"
actix-rt = "2.10.0"
actix-cors = "0.7.0"
juniper = "0.16.1"

[dev-dependencies]
serde_json = "1.0.48"
lazy_static = "1.4.0"
