services:
  backend:
    build: ./Milk-Backend
    ports:
      - "5000:5000"

  webview:
    build: ./Milk-WebView
    ports:
      #TODO: Before deploying, do the port fowarding
      - "5173:5173"
    #depends_on:
      #  - backend
  redis:
    image: "redis:alpine"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSCODE:?REDIS_PASSCODE variable is not set}"
    volumes:
      - db:/var/lib/redis/data
    env_file:
      - env_variables/.env

networks:
  mynetwork:
    driver: bridge
  
volumes:
  db:
