version: '3.9'

services:
  backend:
    build: ./Milk-Backend/
    ports:
      - "5000:5000"
  webview:
    build: ./fronted
    ports:
      - "5173:0080"
    depends_on:
      - backend
  redis:
    image:"redis:alpine"


networks:
  mynetwork:
    driver: bridge
  

