services:
  backend:
    build: ./Milk-Backend
    ports:
      - "5000:5000"

  webview:
    build: ./Milk-WebView
    ports:
      # Before deploying, do the port fowarding
      - "5173:5173"
    #depends_on:
      #  - backend
  redis:
    image: "redis:alpine"
    #add redis volume 

networks:
  mynetwork:
    driver: bridge
  

