services:
  backend:
    image: milk-link_backend:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
  webview:
    image: milk-link_webview:latest
    ports:
      - "${WEBVIEW_PORT}:5174"
    depends_on:
      - backend
  redis:
    image: redis/redis-stack-server
    # I'll explain each one of this arguments:
    # --requirepasss: for adding the password (we don't need different users)
    # --loadmodule: for having different redis modules, in this case the Re-Json
    # --apendonly: for not flushing whenever the redis-server get's down
    # --dir: for the directory route which the data will be saved
    # --dbfilename: in this case is just for creating the dump file
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSCODE:?1234}" --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so --appendonly yes --dir /data --dbfilename dump.rdb
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - db:/data
    env_file:
      - .env

volumes:
  db:

