name: deployment_personal_vm

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ~/.keys
      - run: touch ~/.keys/PERSONAL_VM_KEY.pem
      - run: echo "${{ secrets.PERSONAL_VM_KEY}}" >> ~/.keys/PERSONANAL_VM_KEY.pem &&  chmod 600 ~/.keys/PERSONANAL_VM_KEY.pem 
      - run: cat ~/.keys/PERSONAL_VM_KEY.pem
      - name: entering personal vm
        run: ssh -i ~/.keys/PERSONANAL_VM_KEY.pem -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: pulling new code
        run: git pull
      - name: Re-Runing compose
        run: docker-compose up --build
